### ISSUE TITLE
The API schema is invalid

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1132]
Go to https://grand-challenge.org/api/ and at the very far bottom right there is a validate button. Click on it, it returns:

```
{"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"additionalProperties","message":"object instance has properties which are not allowed by the schema: [\"$schema\",\"anyOf\",\"definitions\"]","schema":{"loadingURI":"http://swagger.io/v2/schema.json#","pointer":"/definitions/schema"},"instance":{"pointer":"/definitions/Answer/properties/answer"}}]}
```

**Comment by jmsmkn** [comment]
@silvandeleemput do you know why this is? We should fix it before integrating elsewhere.

**Comment by silvandeleemput** [comment]
@jmsmkn It appears to be related to the new Answertype schema, but I don't know why yet. I am looking into it.

**Comment by silvandeleemput** [comment]
The external validation (https://validator.swagger.io/) of our served schema is not Swagger 2.0 compliant. This is because the served Answertype schema has certain unexpected properties (nested definitions, schema definitions, and anyOf keyword),   With OpenAPI 3. 0 on the horizon, we might want to move to this more feature-complete formatting. 

https://blog.readme.com/an-example-filled-guide-to-swagger-3-2/?utm_content=buffer5a042&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer
