### ISSUE TITLE
Allow readers to take a reader study again

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1188]
Required for both test and training studies. 

* How should we handle old answers?
* This should also work with say, editing reader study answers.

**Comment by MikeOverkamp-diag** [comment]
I think it would be a good idea to make this optional, i.e. add a `Allow readers to take this ready study more than once` checkbox when setting up the reader study, because I do not think all editors would want this behavior.

I think for statistical purposes it would be best if we are able to retain all answers. Otherwise, we would lose valuable information on case difficulty, as the expectation is that readers will increase their performance over time. My suggestion would be to add something like an `iteration` field to the `Answer` model, to be able to determine which answers should be grouped together. (I would like to call this field `session`, but since we already have a `Session` model and the way I see it, an iteration can span more than one session, we need a different name to prevent confusion)

If we allow users to restart we should probably update the reader interface a bit as well. Initially we would just have the `Launch this reader study` button. But if answers for the reader already exists, it would be split up in two separate buttons: `Continue current reader study` and `Restart reader study`.

**Comment by jmsmkn** [comment]
We use Django Simple History elsewhere to store different versions of the same object https://django-simple-history.readthedocs.io/en/latest/querying_history.html. You can limit it by field, etc, and it works well. I'm wondering if this will be easier to manage, especially with question editing? 

Then, the different sessions would be the different levels in the object history. We would then need to handle if the number of levels is different for any reason. Maybe we still end up with a `session` or `trial` object that tracks when the user started the test, and filter the different answers between the different times in there for each user and study.

**Comment by jmsmkn** [comment]
Where are we with this now? I think with editable reader studies this is there, but probably needs documenting on how to do this.

**Comment by MikeOverkamp-diag** [comment]
I think that is a good basis for this, but ideally I'd also like to give readers the choice between restarting and continuing a reader study when appropriate.

**Comment by jmsmkn** [comment]
I think that a pitch for such a feature should be made if this is still important.
