### ISSUE TITLE
Remove single polygon annotations

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1226]
Do not work

**Comment by HarmvZ** [comment]
Paul just notified me that this has been fixed in https://github.com/DIAGNijmegen/rse-cirrus-core/pull/547. Most likely by addition of this line: https://github.com/DIAGNijmegen/rse-cirrus-core/blob/2e1c55e392166131a54388522ac885c4c517233a/src/cirrus/DIAG/CIRRUSCore/Modules/Scripts/python/cirrus/workstations/core_web/reader_study/cso_serialization.py#L483

I will close all related PRs.
