### ISSUE TITLE
Include slice thickness in mha generated from DICOM

### ISSUE THREAD

**Issue by nlessmann** [comic/grand-challenge.org#1297]
The calcium scoring algorithm is one of the very few algorithms that use both the slice spacing and the slice thickness. The slice spacing is not a standard header field in mha/mhd files, but the algorithm checks anyway if there is a "SliceThickness" header field. It would be nice if the DICOM importer would add this information to the mha header when available in the DICOM header.

**Comment by nlessmann** [comment]
I also noticed that these kind of custom headers are removed during the import of mha files. So if I upload an mha file with a SliceThickness header field, it is not actually available to the algorithm.

**Comment by jmsmkn** [comment]
Yes, any headers that are not explicitly maintained are scrubbed. The kept headers can be updated [here (metaimage import)](https://github.com/comic/grand-challenge.org/blob/master/app/grandchallenge/cases/image_builders/metaio_utils.py#L58) and [here (DICOM import)](https://github.com/comic/grand-challenge.org/blob/master/app/grandchallenge/cases/image_builders/dicom.py#L27).

**Comment by nlessmann** [comment]
Thanks, I will try to prepare a PR.

**Comment by bramvanginneken** [comment]
Is this the intended mechanism to associate additional info with a scan (series) that you upload to grand-challenge? I have for example 1000 scans I want to add and for each scan a short text describing some clinical history of the subject on the scan. Should I put this in a header field? Probably not (always), because what if you later want to add info? For DIAG archives, at least how @cjacobs1 uses them, we have a folder named derived in each archive, and there you have subfolders and information you want to associate with a series would be in that folder and the filename is the SeriesInstanceUID. I think we need to discuss how to do such things for grand-challenge archives.

**Comment by jmsmkn** [comment]
No, use the case_text in a reader study. Dumping stuff into the mha headers
is only a hack to get all of this to work with CIRRUS right now. We cannot
do this for pathology so need to find a better way to support both
modalities, and support more meta info outside reader studies.
