### ISSUE TITLE
Use DIAG dicom importer

### ISSUE THREAD

**Issue by MikeOverkamp-diag** [comic/grand-challenge.org#1378]
A dicom importer written by @cjacobs1 is available in DIAG. Many of the issues we encounter with importing dicom files should not occur when using this importer. We should look into what is needed to use that importer rather than our own image builder when users upload dicom volumes.

**Comment by pkcakeout** [comment]
I would like to chime in here. I do not think that the DIAG-dicom importer is very good in all circumstances. in fact, it has many, many limitations:

- It cannot read MR data with unaligned slices (x)
- It cannot read color images
- It cannot read scans with irregular slice spacing (x)
- It cannot read color depths deeper than 16 bit. In fact it only can read 16-bit color depth image images, converting 8 bit to 16 where necessary. You loose the original pixel type.

The (x)-marked limitations are actual design features. There are likely a lot more limitations. It _appears_ that this thing did not have many issues because @cjacobs1 intervened with many thrid-party data sources, but it is very much geared towards our hospital's CT data - and it works very well for that type of data. However, characterizing it as "time tested" is a gross over-simplification of what we have:

Grand-challenge will attract by definition many scans from many different hospitals, and we are not bound to only receive CT data. This is exactly the situation in which the diag-dicom loader is not well tested. I dare to say - having worked on in for the deep-learning image, that it will likely be as unstable as what we have now!  

@cjacobs1  Probably handy to have you comment on this as well. 

-----------

Having the a Python implementation of a python loader would be more beneficial for our group, I think since we nowadays have more Python in-house knoweldge than C++ knowledge. I would therefore assume it would be a allround better approach to fix the current Python implementation using the C++ code as a guide. DICOM is a bad and broken standard, we are not able to fix that. There always will be things we need to fix manually.

If we still want to use the DIAG dicom loader I would suggest having a look at the uok-base image that Nikolas and John-Melle made. They automated the builds for python over there and you can use their code as a basis on how to build the diag-image loader for python yourself. If you have questions about the bindings themselves, feel free to contact me as I am the original author of those. Colin knows most about the dcmtk-interface things, I know a bit.

**Comment by pkcakeout** [comment]
Note: The discussion on this ticket is (temporarily?) happening on an email thread instead in here.

**Comment by jmsmkn** [comment]
Following discussions offline we have decided not to do this, and will continue with #1279, #1293, #1301.
