### ISSUE TITLE
Make color of algorithm job status configurable

### ISSUE THREAD

**Issue by nlessmann** [comic/grand-challenge.org#1599]
The color in the algorithm results table indicates only whether the docker image was successfully run or not. But many algorithms can actually run without any error and still produce a negative result. For example, the vertebra segmentation algorithm can run without problems but also without finding a single vertebra in the entire image. I've used the jinja template to show some text to the user in that case because this usually means that something is wrong with the input data. It would be very nice if it was possible to turn the status from green to orange based on the data in the results.json file (maybe by allowing the editors to configure a jinja-style if/else statement for this?). That way, we could highlight jobs with problems and distinguish them from really successful and really failed jobs.

**Comment by jmsmkn** [comment]
The job state causes some confusion - it tracks its execution status and follows the Celery states options very closely (https://docs.celeryproject.org/en/stable/reference/celery.states.html#misc). So, when `job.status == Job.SUCCESS`, this doesn't mean that the algorithm was successful, only that the scheduled job completed without errors. Maybe "Completed" would be better terminology, but again, I want to stick to the Celery states as this is really what `status` is tracking.

For this, I want to keep a binary status so that we know whether to continue with the other tasks in the workflow (a DAG of jobs). If we add an intermediate state (completed with warnings) how would we know whether to continue or not? Would depend on what the downstream could handle.

Remember that you can always set the failed state by raising an exception with a message. You could add an automated quality control step after post-processing that checks, say, if you have detected any vertebra and if not raise an exception and mark it as failed (as it really failed). You know that your algorithm should detect at least 1, but what happens if you only detect 3? Could depend on the input image, in which case, this needs to be a manual QA step. For this, maybe a new field on the job would work, something like `qa_warning_message` which is default to empty string, and sets this warning state if non-empty. What we can also do is parse stderr (that way you can call "warnings.warn" when you do your automated qa step) and save these in a warnings field on the job, and then we can get a "completed, but with warnings" automatically out. We would need to see how to pass these to the user.

**Comment by nlessmann** [comment]
To me, it would make most sense to use the results.json file for this instead of introducing another field. The algorithm can then perform some checks and report all relevant information next to any other ouput in the json file, which anyway needs to be part of the input of other tasks in a multitask workflow. Subsequent tasks could then decide based on the information in the results.json whether they can proceed with this input or not, and this could be different for every task.

The GC GUI is then just another "consumer" of the algorithm's output - with the jinja template it's already now possible to customize what is displayed to the user based on the content of the results.json file. So the only thing I'd like to be able to do is to also influence the color of the job status in the results table in the same way, by parsing the results.json in a customizable way. The if-statement in the template that now does something like `if job.status is SUCCESS then color = green` would become `if job.status is SUCCESS then (if CUSTOM_CONDITION then color = orange, else green)` where the custom condition should be configurable per algorithm and could be something like `result_dict.detected_objects == 0`. Probably it's a bit more complicated, but this is what I had in mind with this feature request.

**Comment by jmsmkn** [comment]
I know, but the trouble is that making lookups in the JSON structures is really expensive, especially if we need it to be custom per algorithm (eg, setting `CUSTOM_CONDITION`) as in those cases we have to do the work in Python rather than the db to avoid SQL injection attacks. It would make rending things like the list view, and the API views very difficult as we only have a few ms to play with so we already have to play a lot of tricks to make these views work.

I want to move away from dumping everything in a JSON blob and putting anything common in proper fields, and I think warnings are a standard thing we can extract. It is standard for applications to report warnings on STDERR, so I would rather keep to that convention, and if you do not need a manual QA step then that makes things much easier. For the dependencies, you can already make those lookups in the JSON.
