### ISSUE TITLE
add original input name to the output names

### ISSUE THREAD

**Issue by aswolinskiy** [comic/grand-challenge.org#1634]
Currently the input files appear with random strings as names in the algorithm-input directory and the output files therefore don't contain the original input name (currently shown in details). Thus a user has to rename the images one by one manually and if they when on a batch of images it would be impossible or difficult to know which output(s) belong to which input. A simple solution would be to keep the original input name (shortening the random name-part would be nice too). Or to automatically append the input name to all output files.

**Comment by jmsmkn** [comment]
I will allow the user to download the files as their original names from your algorithm container. If you do not want the input image in the filename do not add it in your container. You can also shorten it in your container, you are responsible for that, not grand challenge.

The reason we do not use original filenames is that we import hundreds of images at the same time, with DICOM this can be tens of thousands of individual files that all need to be accounted for correctly at import time. These import processes, therefore, take a long time and work in parallel and cannot communicate with each other. We need the resulting files to be unique, so to guarantee that from processes that cannot communicate with each other we use UUIDs, they have all the properties we desire, the downside is that they're long. But, like I said, you can rename it.

It is far from impossible to find out the original filenames, it's all in the API. Read this comment https://github.com/comic/grand-challenge.org/issues/1627#issuecomment-736561991

You shouldn't be clicking in an interface to download many files from a page, script it. This is how you download all of the results from an algorithm into a folder for each job including json, images, and all the information you need to know what is the output for what https://gist.github.com/jmsmkn/2f9c4421900e8fbeff22281e8884a6ec

**Comment by jmsmkn** [comment]
The way to do this would be to use the `download` attribute of an anchor, but this [does not work for security reasons with cross-origin requests](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download). Now, we need to use CloudFront so that we can use globally available workstations. We cannot use the same domain for CloudFront as it was decided long ago to allow challenges to get their own subdomains. So, we have to use cross-origin requests for images, so we cannot use the download attribute.

There are some [hacky workarounds](https://stackoverflow.com/questions/49474775/chrome-65-blocks-cross-origin-a-download-client-side-workaround-to-force-down?answertab=votes#tab-top) using JS but performance is terrible as it stalls the downloads for ~1 minute, and is not good for large data (especially medical images). 

We cannot rename the files in storage, [as detailed above](https://github.com/comic/grand-challenge.org/issues/1634#issuecomment-738633621). I cannot see a reasonable way to implement this, so closing.
