### ISSUE TITLE
UserAutocomplete test_func performs too many queries

### ISSUE THREAD

**Issue by amickan** [comic/grand-challenge.org#1692]
While creating #1691 , Harm and I noticed that the `test_func` within `UserAutocomplete` is not efficient:
https://github.com/comic/grand-challenge.org/blob/c4d4490304bf085bb1b3c2a8b5e1a525f0969a04/app/grandchallenge/groups/views.py#L46-L57

See the test for more information: it performs 20 queries, 16 of which are for permission checks and many of those are not actually necessary:
https://github.com/comic/grand-challenge.org/blob/0ebc70b374cdfd3335902274d73360711dfb220c/app/tests/groups_tests/test_views.py#L191-L192

**Comment by jmsmkn** [comment]
Indeed, I think this function is well covered by tests apart from `"algorithms.change_job"`. I'm pretty sure that they're all necessary as only editors of those objects should be able to access this. `any` should stop the generation as soon as there's a match, right? So if you do this for an algorithm editor then it should return early, I think? 

Otherwise, I think this is still tricky to construct as the `UserObjectPermission` is foreign keyed to `ContentType`, so we would need to look up all of those first before filtering `UserObjectPermission`. We shouldn't look for groups here as that adds too much coupling between the code. Or, we can do this via a new global permission. What do you suggest?

**Comment by jmsmkn** [comment]
I'm going to close this as I think that the performance is fine.
