### ISSUE TITLE
Named overlays as algorithm job outputs

### ISSUE THREAD

**Issue by HarmvZ** [comic/grand-challenge.org#1720]
For an algorithm with multiple image outputs, the outputs are shown as overlays in the workstation but they are named as "Overlay n", "Overlay n+1", etc. see this algorithm for example: https://grand-challenge.org/algorithms/segmentation-of-advanced-amd-biomarkers-in-oct/. It would be nice if the overlays are named so that the OverlayPlugin can display those names in the dropdown box.
According to [the processor documentation](https://comic.github.io/grand-challenge.org/processor.html#processor-outputs), the images should be mentioned in the result.json. We could extract the image name and store it in the `description` field of the `ComponentInterfaceValue`. The overlayplugin can then use these values as labels for the overlays.

**Comment by jmsmkn** [comment]
We should not parse out `results.json`, experience has demonstrated that it does not work at all and we want to deprecate that and change the spec in the documentation.

The way to do this is to directly create a new `ComponentInterface` for each of the overlays first, then assign them as outputs to the algorithm. The algorithm would then need to put those overlays in a specific place, rather than dumping everything in one folder. The `ComponentInterfaceValues` would then be populated from that definition https://github.com/comic/grand-challenge.org/blob/6a53669998619924aa28346bd8d98d398de17e9a/app/grandchallenge/components/models.py#L140.

**Comment by jmsmkn** [comment]
This should be done now, but need to double check.
