### ISSUE TITLE
Add image preprocessing plugin workstation config values

### ISSUE THREAD

**Issue by HarmvZ** [comic/grand-challenge.org#1729]
The workstation config needs to be extended to support new values implemented in https://github.com/DIAGNijmegen/rse-cirrus-core/pull/1001.

Fields to be added:
- `show_image_preprocessing_plugin`: `BooleanField` with default value `False`
- `enabled_preprocessors`: `JSONField` containing an object with (for now) a single key `enabled_preprocessors` with a boolean value, e.g. `{ "contrast_enhanced": true }`

**Comment by jmsmkn** [comment]
Should `enabled_preprocessors` just be an array? Would need to refactor the implementation anyway if you wanted to add any further configuration. Then, we could combine both of these options into one field, with default being an empty list which would cover `show_image_preprocessing_plugin=False`.

**Comment by HarmvZ** [comment]
Ah you're right, that's much easier. I will change it in the PR on the cirrus side.

**Comment by amickan** [comment]
I tried implementing this as an `ArrayField` but it turns out that this is not easily done. Something goes wrong with the validation of the answer choices that Harm and I couldn't fix just now. Alternatively, we could instead implement this as a boolean checkbox `enable_contrast_enhanced_plugin`, which then gets converted to a list with that is either empty (when it's not checked) or contains `contrast_enhanced` before the configuration file gets send out. @jmsmkn , what do you think about this? I hope what I said makes sense.

**Comment by jmsmkn** [comment]
> Alternatively, we could instead implement this as a boolean checkbox enable_contrast_enhanced_plugin, which then gets converted to a list with that is either empty (when it's not checked) or contains contrast_enhanced before the configuration file gets send out.

Sounds good to me, you can do that conversion with a method on the serializer and use `SerilizerMethodField(...)` from django rest framework.
