### ISSUE TITLE
Add image identifier to csv output for multiple bounding box reader study

### ISSUE THREAD

**Issue by brambozz** [comic/grand-challenge.org#1730]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jmsmkn** [comment]
Download the image CSV file, the information is in there.

**Comment by brambozz** [comment]
I see, thanks! Is there a reason not to include the image name as well? I feel that makes it easier to parse results, right now I have to do extra requests only to get the image name.

**Comment by jmsmkn** [comment]
You have to download 1 extra file, all the information is in that. It is this way as parsing this information server side takes a long time, and there is only so much we can do in 200ms. If this takes too long, it is possible to take down the all of our servers by occupying all of the workers, that was happening with the old CSV export so that is why it was removed and will not be brought back.
