### ISSUE TITLE
Make it easier to find the form for creating a challenge

### ISSUE THREAD

**Issue by nlessmann** [comic/grand-challenge.org#1801]
The link to the "Create your own challenge" blog post is very well hidden - it used to be in the footer, but now it has been replaced by "Create your own reader study". Maybe that's me, but I find it very hard to find where I can create a challenge.

How about adding a button on top of the page:

![sketch](https://user-images.githubusercontent.com/773597/114011686-cf2ec600-9865-11eb-87ca-ae5af88c5bc5.jpg)

This could lead to the blog post that explain how to create a challenge / reader study / etc

**Comment by jmsmkn** [comment]
It's still in the footer but moved to a blog post rather than a flatpage: https://grand-challenge.org/blogs/create-your-own-challenge/

For reference: the URLs have structure, so if you're on a list page you can always append `create/` to the URL and usually you will get the object creation page (subject to authorization). `/challenges/create/` is the page you need.

I don't really know what to do about this, when we had the button there we got so many junk challenges created that we need to periodically clean up. It is really difficult for us to communicate the difference between signing up for grand challenge, joining a challenge to participate in it, and creating a challenge. If we do add this back we should make it more difficult to make a challenge public, we should have some sort of review to maintain some quality of the content, and indicate that a particular challenge is not public and not indexed by search engines. I would rather people read the blog post to have a sense of what organising a challenge means, I have made the button more prominent there:

![image](https://user-images.githubusercontent.com/12661555/114022193-cd6aff80-9871-11eb-8f86-86409feb21d5.png)
