### ISSUE TITLE
Refresh access for users that apply or lose verification after placing access request

### ISSUE THREAD

**Issue by kiranvaidhya** [comic/grand-challenge.org#2461]
**Is your feature request related to a problem? Please describe.**
I see this for algorithms that auto-accept verified users now. Users that place an access request for an algorithm first and then apply for verification do not get automatically accepted after their verification is successful.

**Describe the solution you'd like**
If a user passes or loses verification, all their access requests can be looped through and updated depending on the request handling rule per algorithm/challenge/reader study.

**Comment by jmsmkn** [comment]
Related request:

> I see that if algorithms are set to accept requests from verified users only, then this works nicely, but what happens when a non-verified users makes a request? Is that "pending" and needs manual approval? If that is the case, would it be possible to either prevent people from requesting, or getting an automatic rejection with a message saying something like "Please make a new request using a verified account."?

**Comment by ammar257ammar** [comment]
Is user verification performed only in Admin?

![Screenshot 2024-08-06 at 10 05 45](https://github.com/user-attachments/assets/b530ad94-195e-47b8-98f0-cd7cde26d057)

**Comment by jmsmkn** [comment]
Yes

**Comment by ammar257ammar** [comment]
> If a user passes or loses verification, all their access requests can be looped through and updated depending on the request handling rule per algorithm/challenge/reader study.

1- If the user asked for verification after making permission requests, do we want to re-accept previously rejected permission requests after user has verified their account, or just accept the pending requests?

2- Also, do we want to revoke previously accepted permission requests if the user verification status has changed (to denied) after it had been approved before?

> I see that if algorithms are set to accept requests from verified users only, then this works nicely, but what happens when a non-verified users makes a request? Is that "pending" and needs manual approval? If that is the case, would it be possible to either prevent people from requesting, or getting an automatic rejection with a message saying something like "Please make a new request using a verified account."?

3- Do we want to automatically reject permission requests when request handling is MANUAL, if the user is not verified?

**Comment by jmsmkn** [comment]
1 No
2 No
3 No

**Comment by ammar257ammar** [comment]
**Have anyone had this issue before?**

I am trying to import `from grandchallenge.algorithms.models import AlgorithmPermissionRequest`

in `app/grandchallenge/verifications/models.py`

But the app crashes and I get the following error

![Screenshot 2024-09-05 at 11 00 29](https://github.com/user-attachments/assets/1fc7cc7e-90c3-476c-8c82-aaba5897d957)


the same error happen when importing `from grandchallenge.archives.models import ArchivePermissionRequest`

**Comment by pkcakeout** [comment]
My guess: you are importing a model where you are not allowed to. I forgot about the specifics of this, but it _is_ somewhere in the Django documentation. You need to use local imports instead. I think this happens if you import `models.py` in an `admin.py`, for example, but not super sure anymore!

Btw: This is probably something you are stuck on, right? I would see a problem if you post this as a question on Teams as well. Then you might get faster response times, especially if you are really stuck on this...

**Comment by ammar257ammar** [comment]
Thanks Paul! helpful indeed. And yes, I am stuck on it. I posted it here to keep it documented as a problem encountered while solving this issue. I will put it on Teams as well next time.

**Comment by jmsmkn** [comment]
The problem will only appear when you add any new imports. So look at what is changed to any imports in you local git repo, then comment stuff out and try and break the cycle.

You can see that the problem is in `algorithms/models.py` when trying to import from `components/models.py`. But on main that already happens. So the problem is with some changed you made in `components/models.py`.

90% of the time the solution is a local import, but sometimes dependencies need to be moved to a common location outside of the loop.
