### ISSUE TITLE
Homepage carousel looks bad on small screens

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#2949]
748px wide:

<img width="749" alt="image" src="https://github.com/comic/grand-challenge.org/assets/12661555/f25c6f5b-83e9-4efd-b18b-17f3bf752a33">

500px wide:

<img width="505" alt="image" src="https://github.com/comic/grand-challenge.org/assets/12661555/46c8fa95-e900-4b39-bc38-a7ae506cd170">

**Comment by james-milburn-crowe** [comment]
Think the fixes here would be: 
 < 500px - can be very similar, but ensure the image is centered
500-748px - I'll try a couple of options, but image and text should not be cut, and whitespace in the middle should prehaps reduce in size

**Comment by pkcakeout** [comment]
Probably better to use `dp` instead of `px` - `px` really does not work well on high-density screens if I am not mistaken!

**Comment by james-milburn-crowe** [comment]
ok, looks like the issue here is that we use columns inside a carousel, and it looks like this makes it overflow the container borders (So at medium breakpoints, the cutoff image extends out into the whitespace, but is hidden). 

Removing col-12 col-md-3 for the carousel items gives a good result, and we could just let bootstrap carousel handle the sizing

**Comment by james-milburn-crowe** [comment]
![Screenshot 2023-08-08 180846](https://github.com/comic/grand-challenge.org/assets/14093674/97321259-58f2-4dde-bb2e-6647fd0f4ce0)
 Here's what's currently happening

there's this way of adding columns inside a carousel - https://stackoverflow.com/questions/48648916/bootstrap-4-carousel-columns-instead-of-carousel-item  we just have to make some inner row/column setups for it

**Comment by james-milburn-crowe** [comment]
ended up working yesterday on some of the file deduplication things, instead of this, but it's finished today

**Comment by jmsmkn** [comment]
I think this issue already existed but the corners of the image are not rounded on md+ screens:

<img width="749" alt="image" src="https://github.com/comic/grand-challenge.org/assets/12661555/f25c6f5b-83e9-4efd-b18b-17f3bf752a33">

**Comment by james-milburn-crowe** [comment]
strangely, this is only on the first image loaded - all others are rounded on md+

**Comment by jmsmkn** [comment]
Could also be the shape - the image is square or portrait rather than landscape.

**Comment by james-milburn-crowe** [comment]
just took a quick look at this at the end of the day - it looks like carousel-img-container is the culprit - from core.css

```
@media only screen and (max-width: 768px) {
  .text-truncate-container {
      height: 12rem;
  }
  .text-truncate-container p{
      -webkit-line-clamp: 3;
  }
  .carousel-img-container {
      height: 15rem;
  }
}

@media only screen and (min-width: 768px) and (max-width: 1200px) {
    .carousel-img-container {
        height: 10rem;
    }
    .text-truncate-container {
      height: 10rem;
    }
    .text-truncate-container p {
        -webkit-line-clamp: 3;
    }
}

```

It, I think, locks the size of the image container to be larger than the available space, and then the rest of the layout, which has percentage based sizing, chops off the rest of the element

Without this class, images end up slightly larger, but have properly shaped edges. We could set the height directly on the images, or remove it altogether and let image proportions change with the rest of the div sizing.

Without height: 15rem applied

![without_sizing](https://github.com/comic/grand-challenge.org/assets/14093674/f74859fc-9a16-4fae-be37-41ab2b0c32cb)
![without_sizing_rect](https://github.com/comic/grand-challenge.org/assets/14093674/96d16825-bb4b-4718-aa6c-800ea6ad4d4e)


With height 15rem applied to the image, rather than the carousel-image-container div


![capture_with_sizing](https://github.com/comic/grand-challenge.org/assets/14093674/b99a4f07-2144-4fa4-88c4-1d870ca9dc7b)
![Capture_with_sizing_rectange](https://github.com/comic/grand-challenge.org/assets/14093674/dd87233d-9260-462b-8b2d-a677f30dcdf5)

**Comment by jmsmkn** [comment]
Make a PR if you think that you have a solution.
