### ISSUE TITLE
Documentation sidebar not scrollable

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#2999]
On smaller screens when the sidebar is expanded you cannot navigate through all of the documentation.

**Comment by amickan** [comment]
I think what you're referring to is because the sidebar is "sticky" so that it remains visible when you scroll through content next to it. Downside indeed is that the sidebar itself is not scrollable until you come close to the end of the content on the right. We could instead just go for the default, static positioning of the sidebar. It will then disappear as you scroll through the content on the right, but it will always be fully scrollable.

**Comment by jmsmkn** [comment]
Yes I think change it as we have a lot of content now.
