### ISSUE TITLE
Hanging protocol previews sometimes broken in list view

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#3009]
**Describe the bug**
See Main with draggable smaller view or Tertiary on https://grand-challenge.org/hanging-protocols/:

<img width="362" alt="Screenshot 2023-09-01 at 08 44 14" src="https://github.com/comic/grand-challenge.org/assets/12661555/2afe6464-9566-4f34-8be3-4677ec63dcef">
<img width="362" alt="Screenshot 2023-09-01 at 08 44 26" src="https://github.com/comic/grand-challenge.org/assets/12661555/41877790-2ebd-4692-b1d5-b2a1fb8edd82">

The SVG is correct but the grey previews with names are wrong. On the detail pages they look fine:

https://grand-challenge.org/hanging-protocols/main-with-draggable-smaller-view/
<img width="1148" alt="image" src="https://github.com/comic/grand-challenge.org/assets/12661555/557f3639-d9ed-4dee-99e2-aff8f33ebbce">
https://grand-challenge.org/hanging-protocols/tertiary/
<img width="1144" alt="image" src="https://github.com/comic/grand-challenge.org/assets/12661555/5868d20e-6c20-4dd1-a1d3-4379cff2f760">

**Comment by james-milburn-crowe** [comment]
great - looking at it

**Comment by james-milburn-crowe** [comment]
looks like all the elements are still being placed, but that they're ending up covered by the main box

**Comment by james-milburn-crowe** [comment]
z index is being set to -1 and -2 on those elements, causing them to appear behind the card.

**Comment by james-milburn-crowe** [comment]
Ok, a little more research: The only ones that use a negative z-index are those hanging protocols, and there it doesn't render correctly. It seems to render fine on the other view, because it's not got a card it can end up behind.

Digging into the js, it looks like we translate "order" to the inverse of its z-index, and these are the only one using orders

I think shunting the cards to z-index -99 or just turning off their background color is probably the simplest fix

alternately, we could start our highest ordered object at a z index equal to the number of viewports. That way, when someone creates a 5000 viewport hanging protocol, it'll still render correctly (At least with regard to correct layering)

**Comment by jmsmkn** [comment]
From the schema we know that there are a maximum of 20 viewports.

**Comment by jmsmkn** [comment]
Closed by #3011
