### ISSUE TITLE
Blog post can overflow into sidebar

### ISSUE THREAD

**Issue by pkcakeout** [comic/grand-challenge.org#3095]
Blog post can overflow into the sidebar:

![image](https://github.com/comic/grand-challenge.org/assets/11632379/1e45b85e-42e8-4913-af30-b089d0c89b66)

Easiest fix: `overflow: hidden`

**Comment by ammar257ammar** [comment]
@pkcakeout can you point me to which blog post the image above belongs to?

**Comment by ammar257ammar** [comment]
I see from looking at the blog posts that images has `max-width:100%` which should keep then in the blog column.
Also, The blogpost body field in the create form is just a text box (screenshot below), so how styled posts with media (images/video) are created?

![Screenshot 2024-08-01 at 14 53 27](https://github.com/user-attachments/assets/b2a7f49c-2fc5-4df1-ac15-6882913a5c88)

**Comment by jmsmkn** [comment]
You need to create the post first. Then you can edit it and drag and drop images onto the markdown block.

**Comment by jmsmkn** [comment]
> The blogpost body field in the create form is just a text box 

That is the description field.

**Comment by pkcakeout** [comment]
Everything that James said. And I then just uploaded a very wide image, which caused the menu to overlap with the blog-content. Maybe when resizing of the browser window is required for this to appear as a response to reactive content, I cannot quite remember the details. The blog-post does not exist in this form anymore, because I removed the image. I mean, it looked quite bad thanks to this bug.

**Comment by ammar257ammar** [comment]
I tried to reproduce this issue (screenshot below). I uploaded 3 wide images (4000px, 3000px, 2000px) with different heights. However, they are automatically given the class "img-fluid" which constrain their width to 100% so they don't exceed the blog column. I tried resizing and different screen sizes and it looks good in all cases.

![Screenshot 2024-08-06 at 08 43 50](https://github.com/user-attachments/assets/d9aff3b2-5386-47fb-aa31-8ba7a2aa9d84)

**Comment by pkcakeout** [comment]
Ok... I went hunting for you. And found one. The recipe is a bit vague, nad maybe it is not such a big problem afterall. But see here:

![image](https://github.com/user-attachments/assets/c3f40331-cf7e-4c5f-87cc-eaf7e0981b3f)

Test case: https://grand-challenge.org/blogs/october-2023-cycle-report/

Note: It is the footer-image that overflows, so I just went ahead and deleted all intermediate `<p>` tags. Here a video on how to reproduce (enable audio for explanation):

https://github.com/user-attachments/assets/ffe21088-393d-4eb4-a55a-047e0a692110

**Comment by ammar257ammar** [comment]
Thanks a lot Paul for the test case and explanation. That makes sense since the image does not have the class "img-fluid" that controls the width and makes it looks rights on all sizes. Adding the class in the inspector solved the issue (screenshots below)

Since the editor adds that class to uploaded images automatically by default (as shown above in my comments), should we interfere with this now and add css for images in older posts? Moreover, images in the posts does not have classes, and the editor is for markdown and does not provide such a capability natively unless you hardcode the <img> element as html (that is a hassle anyway and it is not expected from editors to write html in there) .That means, css rules targeting them will apply globally on the post, and that can cause other problems.

`overflow: hidden` needs to be applied on the parent of the image tag (a paragraph `p` in this case) which also does not have any class or id to identify.

Applying the same rules as the class `img-fluid` on `img` tags in general for posts would solve the problem but it hard to anticipate what would be affected with it later. Also, we can fix the images that we know of (or when we encounter one) by editing the post, while the new ones will have the class and thus have no issue with that. 

Before
![Screenshot 2024-08-06 at 11 06 14](https://github.com/user-attachments/assets/6c7a33ef-232e-481e-b435-d1c4c2c110bf)

After
![Screenshot 2024-08-06 at 11 06 31](https://github.com/user-attachments/assets/0df0b798-8e20-49b3-9478-5f60f82d976a)

**Comment by pkcakeout** [comment]
Ah ok... then maybe this bug is superseded by another way of embedding images by now. This is a true possibility. Thanks for going digging. But, I think that this maybe means that this is a "won't fix". We edited most old images so that the bug does not occur, and new images are embedded in the new way where it is not an issue...

**Comment by jmsmkn** [comment]
The tree processor should be adding `"img-fluid"` to all images:

https://github.com/comic/grand-challenge.org/blob/fb5e31b370365a8ef8e478dbd52c7ca7d637923d/app/grandchallenge/core/utils/markdown.py#L14

Why are `<img ` elements not included in that?

**Comment by ammar257ammar** [comment]
Yes, indeed. But that is not possible to know from already published posts. When I make a new post and add images to it, it adds the class, and I tried many uploads with several widths & heights and also re-editing the post several times. So, not sure how it happened.

**Comment by jmsmkn** [comment]
Copy this line and paste it into a blog post:

```
<img src="https://rumc-gcorg-p-public.s3.amazonaws.com/i/2023/10/20/042179f0-ad8c-4c0b-af54-7e81ba389a90.jpeg">
```

It's still a problem and needs to be fixed.

**Comment by pkcakeout** [comment]
Ah, thank you, james for jumping in here. I forgot about that missing piece, that we support verbatim `<img>` tags in the blog posts!

**Comment by pkcakeout** [comment]
:partying_face:
