### ISSUE TITLE
Page title inconsistencies

### ISSUE THREAD

**Issue by HarmvZ** [comic/grand-challenge.org#3556]
Some pages have correct titles:

- https://grand-challenge.org/challenges/ "Challenges - Grand Challenge". 
- https://grand-challenge.org/reader-studies/ "Reader Studies - Grand Challenge"

But some are inconsistent or missing detail:

- https://grand-challenge.org/reader-studies/test-reader-study-harm/ "Grand Challenge"
- https://grand-challenge.org/reader-studies/test-reader-study-harm/progress/ "User Progress - Grand Challenge" (missing reader study name?)
- https://grand-challenge.org/stats/ "Statistics" (missing Grand Challenge?)

This is inconsistent and adds some guesswork when having multiple tabs open or navigating through history.

**Comment by ammar257ammar** [comment]
After discussing the Chris and Anne titles for different pages. I have the following cases where multiple opinions encountered, and considering your advice to follow the breadcrumbs as is, that creates discrepancies that I would like to get feedback on.

Now I am working on the Algorithms app titles, but the cases here span multiple apps so better to address them earlier.

1- 
![Screenshot 2024-10-03 at 11 14 45](https://github.com/user-attachments/assets/55f7daac-d3f9-4100-b3b1-9068d7747b49)

Title (following the breadcrumbs):
Update - 42b594f1-9aeb-4a68-b7a0-780bba560820 - Grand Challenge

OR

Update Job 42b594f1-9aeb-4a68-b7a0-780bba560820 - Test Algorithm - Grand Challenge

2- 
![Screenshot 2024-10-03 at 11 22 52](https://github.com/user-attachments/assets/22938578-3f3d-4315-b0a9-b9b82d0364af)

Title:

42b594f1-9aeb-4a68-b7a0-780bba560820 - Test Algorithm - Grand Challenge

OR

Job 42b594f1-9aeb-4a68-b7a0-780bba560820 - Test Algorithm - Grand Challenge

**Comment by HarmvZ** [comment]
I think the second one is more descriptive in both cases. 

A quick search reveals lots of sources stating that the title should have a maximum of ~60 characters. So we might want to shorten the uuid since that does not really contain useful information. Most of the information is specifically about SEO which is not very important for these nested pages though. Check this for some best practices by google: https://developers.google.com/search/docs/appearance/title-link#page-titles

**Comment by jmsmkn** [comment]
Yeah don't worry about the length right now.

The 2nd example is better in both cases but the breadcrumb mentions Result. Not Job. They should be consistent. Take the lead from the breadcrumb and use Result.

This problem really should be broken down.

### Task 1 - Ensure every page has the title set

Make 1 PR for each of the following applications:

- [ ] ./forums
- [ ] ./codebuild
- [ ] ./statistics
- [ ] ./patients
- [ ] ./workstations
- [ ] ./organizations
- [ ] ./blogs
- [ ] ./participants
- [ ] ./documentation
- [ ] ./hanging_protocols
- [ ] ./forum_conversation
- [ ] ./api_tokens
- [ ] ./serving
- [ ] ./browser_sessions
- [ ] ./products
- [ ] ./core
- [ ] ./anatomy
- [ ] ./studies
- [ ] ./invoices
- [ ] ./incentives
- [ ] ./retina_api
- [ ] ./timezones
- [ ] ./datatables
- [ ] ./publications
- [ ] ./subdomains
- [ ] ./emails
- [ ] ./verifications
- [ ] ./challenges
- [ ] ./algorithms
- [ ] ./cases
- [ ] ./charts
- [ ] ./modalities
- [ ] ./uploads
- [ ] ./admins
- [ ] ./groups
- [ ] ./archives
- [ ] ./workspaces
- [ ] ./policies
- [ ] ./forum_member
- [ ] ./flatpages
- [ ] ./annotations
- [ ] ./components
- [ ] ./github
- [ ] ./task_categories
- [ ] ./teams
- [ ] ./api
- [ ] ./evaluation
- [ ] ./reader_studies
- [ ] ./workstation_configs
- [ ] ./profiles
- [ ] ./pages
- [ ] ./credits
- [ ] ./notifications
- [ ] ./direct_messages
- [ ] ./registrations

In each PR:
- For each template that contains a breadcrumbs section:
  - Ensure the title block exists
  - Ensure the content of the title block matches what is in the breadcrumbs given the constraints of a maximum depth of 3
  - If the breadcrumbs/title do not make sense, create a new entry in task 2 noting the template name and the problem with the breadcrumbs/title

There should be no discussion about these changes, it should be a simple copy paste job. Files outside of one particular app should not be touched.

### Task 2 - Fix incorrect breadcrumbs/title

Go through the following pages and correct the breadcrumb/title:

- [ ] <you will add template names to a tasklist>

Again, for each of these pages make 1 PR per app.

**Comment by jmsmkn** [comment]
#3581 Introduced a new typo in "Uplaods" on app/grandchallenge/cases/templates/cases/rawimageuploadsession_detail.html.

**Comment by ammar257ammar** [comment]
> #3581 Introduced a new typo in "Uplaods" on app/grandchallenge/cases/templates/cases/rawimageuploadsession_detail.html.

Sorry about that, I checked again the other PRs to make sure no typos are there. 
Made a fix #3588

**Comment by ammar257ammar** [comment]
Yesterday, I gathered all the titles/breadcrumbs from all apps to inspect, cluster and make sure the modifications for Task 2 will be consistent across apps.

- In total there are **144 title/breadcrumbs pairs** from **27 apps**
- **14 apps** do not have templates (I put a note next to them in the [issue comment](https://github.com/comic/grand-challenge.org/issues/3556#issuecomment-2391281270))
- **8 apps** do not have template with breadcrumbs (I put a note next to them in the [issue comment](https://github.com/comic/grand-challenge.org/issues/3556#issuecomment-2391281270))

Then I worked on clustering the breadcrumbs into the following patterns:
1. Breadcrumbs with conditional `if` (those are mostly two types: form templates that can be either create or update views, and access request templates that can have a title with `Review access request` or `Request access` depending on permissions)
2. Breadcrumbs with `yesno` template tag: those are basically also conditional but uses the template tag instead of an explicit `if` condition.
**Note**: based on discussion in #3557, all conditional `if` will be replaced with `yesno` tags to make the code more clear and consistent.
3. Breadcrumbs with one segment
4. Breadcrumbs with two segments
**Note**: 3 and 4 are straightforward, the title with be the same segments followed by {{ block.super }} for site name.
5. Breadcrumbs with three segments
Examples:
Algorithms / ALGORITHM_TITLE / Create Image
Algorithms / ALGORITHM_TITLE / Permission Requests
Archive / ARCHIVE_TITLE / Permission Requests
For those, title can either be:
TEXT - OBJECT_TITLE - SITE_NAME
or
TEXT - OBJECT_TYPE OBJECT_TITLE - SITE_NAME
6. Breadcrumbs with more than three segments
Thos are diverse with some special cases, I will put examples here later for discussion.
