### ISSUE TITLE
Failed jobs are taken into account when rescheduling

### ISSUE THREAD

**Issue by miriam-groeneveld** [comic/grand-challenge.org#3635]
**Describe the bug**
When jobs fail due to time limits, the algorithm editor should be able to update these limits and retry. This does not work due to the existence of the failed job: `A result for these inputs with the current image and model already exists.`

**To Reproduce**
1. Go to any algorithm and reduce the time limit so a job will fail
2. Try out the algorithm > it will fail
3. Update the algorithm to a time limit
4. Try out the algorithm with the same input >  `A result for these inputs with the current image and model already exists.`

**Expected behavior**
It should be possible to retry failed jobs.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by miriam-groeneveld** [comment]
Sil ran into this issue. Probably too complicated to discern between different errors, but wanted to document it.

**Comment by jmsmkn** [comment]
That requires the job to be deleted. We do not allow users to delete jobs as this also removes the usage information. So, in order to reschedule the job they need to contact support who can track to make sure the budget is okay, delete the job for them, an optionally handle any scheduling. Separating the usage information would be a massive task, so given there is already an existing workflow for this I don't think we need to do anything here.
