### ISSUE TITLE
Algorithm Image creation suggests required uuid-labeled output

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#3641]
![image](https://github.com/user-attachments/assets/0933e647-e439-48b0-97c5-26f7e9433a81)

The paragraph on output suggests that the output should have a `<uuid>.mha` / `<uuid>.tif` output. Example algorithms create `/output.mha`.

I am not sure what would best clear it up. Perhaps a location alone would suffice? IIRC technically they can also output dicom/nifty and all other parsable image formats.

**Comment by jmsmkn** [comment]
I don't think this is a big issue and do not think that it is worth splitting hairs over this. They need to output a single file, it needs to be mha or tif, the name is unimportant but it's a good idea for it to be something unique, hence the guidance of using a uuid. The fact that it works right now with other things is happenstance.

> IRC technically they can also output dicom/nifty and all other parsable image formats.

They cannot, we [only accept mha or tif there](https://github.com/comic/grand-challenge.org/blob/ca5cc83f9fd46c35423a5a8130a3f5ff9af08da6/app/grandchallenge/components/backends/base.py#L366). We should not change that because standardisation is a valuable feature of the platform.

**Comment by chrisvanrun** [comment]
> I don't think this is a big issue and do not think that it is worth splitting hairs over this. They need to output a single file, it needs to be mha or tif, the name is unimportant but it's a good idea for it to be something unique, hence the guidance of using a uuid. The fact that it works right now with other things is happenstance.
> 
> > IRC technically they can also output dicom/nifty and all other parsable image formats.
> 
> They cannot, we [only accept mha or tif there](https://github.com/comic/grand-challenge.org/blob/ca5cc83f9fd46c35423a5a8130a3f5ff9af08da6/app/grandchallenge/components/backends/base.py#L366). We should not change that because standardisation is a valuable feature of the platform.

Ah, we use a sub-section of builders. Smart. Def, not a big issue.
