### ISSUE TITLE
Preserve order of result columns

### ISSUE THREAD

**Issue by thomasvdheuvel** [comic/grand-challenge.org#545]
I'm not able to change the order of the scores that appear on the result page of https://hc18.grand-challenge.org/evaluation/results/.

When you go to Admin->Evaluation Settings->Extra results columns: I fill in: 
{"Std absolute difference (mm)": "aggregates.absolute_difference.std","Mean difference (mm)": "aggregates.difference.mean", "Std difference (mm)": "aggregates.difference.std", "Mean DICE (%)": "aggregates.DICE.mean","Std DICE (%)": "aggregates.DICE.std", "Mean Hausdorff distance (mm)": "aggregates.hausdorff_distance.mean", "Std Hausdorff distance (mm)": "aggregates.hausdorff_distance.std"}

But when I save this, the order automatically changes to:
{"Std DICE (%)": "aggregates.DICE.std", "Mean DICE (%)": "aggregates.DICE.mean", "Std difference (mm)": "aggregates.difference.std", "Mean difference (mm)": "aggregates.difference.mean", "Std Hausdorff distance (mm)": "aggregates.hausdorff_distance.std", "Mean Hausdorff distance (mm)": "aggregates.hausdorff_distance.mean", "Std absolute difference (mm)": "aggregates.absolute_difference.std"}

**Comment by jmsmkn** [comment]
Sorry about that! In JSON objects are unordered (https://www.rfc-editor.org/rfc/rfc7159.txt), so it's not possible to preserve ordering with the current key:value pair implementation. I want to change the format anyway so that we have for each field:

- Field name: str
- JSON path: str
- # Significant figures: int
- Plus/minus: {Field name, JSON path, # Significant figures}

This would then be stored as an array of fields in the configuration. The plus minus key would mean that you wouldn't need an extra column for standard deviations. We could extend this further to confidence intervals but there hasn't been a case of this so far.

We would need a nice widget to help users enter this text.

**Comment by jmsmkn** [comment]
This looks like a good starting point: https://github.com/jmrivas86/django-json-widget
The JS library provides an editor and a schema validator: https://github.com/josdejong/jsoneditor

**Comment by jmsmkn** [comment]
@poely This has now been deployed and I've fixed the column order for HC18
