### ISSUE TITLE
Information about reference result can be accessed without login

### ISSUE THREAD

**Issue by poely** [comic/grand-challenge.org#547]
When go to https://hc18.grand-challenge.org/evaluation/results/ without login in, you are able to view the results for each case for each submitted result. For example, https://hc18.grand-challenge.org/evaluation/results/1eea1fc1-6917-4773-84fc-30d2ae10b368/ shows per case all the computed variables with 14 decimals precision.

This will leak information about the reference to all users, which should not be the case when you are organizing a challenge. In the case of the HC18 challenge are all users for example able to extract from these statistics, which case number belongs to which trimester.

**Comment by jmsmkn** [comment]
There is a warning about leaking of information in the evalutils docs, especially with regards to reporting case results: https://evalutils.readthedocs.io/en/latest/usage.html#getting-started

You need to do two things:
- Make a new evaluation container, override self._metrics so that the case results are not reported, eg:
```
    @property
    def _metrics(self):
        return {"aggregates": self._aggregate_results}
```
- Once that is done, email me and I will remove the existing case scores from the database.
