### ISSUE TITLE
Add educational challenges section

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#683]
Add an overview of the educational challenges hosted on the instance. 

- Use the same `ChallengeList` as the all challenges page
- Change the title and description
- Add a bool to `ChallengeBase` that determines if this is educational or not
- Update the get quertset method to further filter on `educational=True`
- Add a new url for `/education/`

**Comment by ecemlago** [comment]
Hi @jmsmkn 

What do you think we add the educational icon near the title? Or should we do that below the card?

 <img src="https://user-images.githubusercontent.com/34303271/51921736-49db3b80-23e8-11e9-872e-64fed9e77db0.PNG " width="300" height="500">

**Comment by bramvanginneken** [comment]
I would like to consider a change in design of the cards. Instead of the text at the bottom, it could be nice to have colored tags. Like this

![image](https://user-images.githubusercontent.com/1818749/51994805-d4d43880-24b1-11e9-9e6d-0c5a1ce10388.png)

We could have one color for event, it would say MICCAI 2019 or ISBI 2020. We could have a color for the task Detection or Classification or Registration or Segmentation. onew for the modality, etc Another color block saying grand-challenge or kaggle, another saying: 210 teams, another 345 results. I think if we keep it concise it could work well.

**Comment by ecemlago** [comment]
@jmsmkn should i also implement the filtering? Filtering as Challenge Type: Educational challenge, Grand Challenge (? i do not know how to call the standard ones)

**Comment by jmsmkn** [comment]
It's up to you, is it needed? If so, make a new issue.
