### ISSUE TITLE
Replace mhd/zraw with mha as internal image representation?

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#715]
I think that we should replace mhd/zraw with compressed mha as our internal representation. I think that this would have the following advantages:

- At the moment, we re-write all meta image files to be named out.mhd and out.zraw, which are located at `images/<image.pk>/out.<type>`. This is awkward as everywhere we need to handle two files, sort out which one is the header, and already in the codebase there are a lot of select by file extension statements.
- If we want to share a bunch of files, say, as an ImageSet for training, all of the files will have the same name, and will have to be re-written (including mhd modification) before they're given to the user. 
- We have the `ImageFile.IMAGE_TYPE_MHD` flag but this actually represents 2 types: a header and data container.

I would prefer that we use mha files. Then, we only have to deal with 1 file, we don't need to sort it everywhere, and we can rename it on the fly. This would then be consistent with the tiff representation. We could then serve images from `images/<image.pk>/<imagefile.pk>/`.

I'm fairly sure that this would still be compatible with the Python (SimpleITK), Mevislab and Javascript (ITK.js) loading libraries.

What could break:
- Everywhere that we've made an assumption about getting 2 images:
  - CIRRUS Web 
  - The `get_sitk_image` function (mhd is not used directly by the ophthalmology workstation).
  - Processors: how do the existing algorithms handle mhd?

Any thoughts? cc. @pkcakeout @HarmvZ @haimasree

**Comment by jmsmkn** [comment]
Also, I would continue using compressed data for now, we should talk about storing some images as decompressed as that would allow for streaming.

**Comment by bramvanginneken** [comment]
I am fine with mha. Can you still manually edit the header in a texteditor?

**Comment by jmsmkn** [comment]
Yes, just tried it out with at CT scan in vim and had no problems, in vscode it was slow to open but worked once initialised (a slow plugin). Some editors might run in to memory issues (Atom I know to be particularly bad with large files).

**Comment by pkcakeout** [comment]
I think a switch to MHA is very convenient and a good step forward. We started with mhd+raw only because of js-library limitations, anyway.

However, I would like to say, that I think that is remains important to _not_ code around the assumption of 1 image-1 file. The reason is, that while MHA is quite flexible, we might need to support storage of more complex "images" in the future which still are a compound of multiple images. While not a current issue, slice based images with different slice spacings or even orientations require a lot of meta data, in essence ending up being a collection of several medical images. I think we need to handle this case as well, and the current database structure does this quite well.

------------

> We have the `ImageFile.IMAGE_TYPE_MHD` flag but this actually represents 2 types: a header and data container.

I missed the introduction of the patch, but what I thought was going to happen is that we introduce a type for an image, not the ImageFile. I actually think that the current implementation is incorrect, since the ImageType should tell us about the semantics on how to load a file. The FileType does not really exist.

I would maybe suggest refactoring this and moving the file type up the hierarchy so that we can use it on the Image-Level. then we can also have "deeper" file types if we want, like "Volume" or "slice collection" for unaligned slices, etc.

>  Processors: how do the existing algorithms handle mhd?

Mine are handling both! But we probably need to check on a case-by-case basis.

>  CIRRUS Web 

I quickly checked how much work it would be. It is reality easy. I think it would take me an hour to do the change a a few more hours to get test coverage. But that is it.

**Comment by jmsmkn** [comment]
I think that having it on the `ImageFile` gives us a cleaner separation of concerns. It allows us to represent the same image using different formats, say, give me the jpeg for a thumbnail or the mhd/tiles if I'm using a viewer. Then, `Image` keeps the concept of a volume of data, and how it is represented is separated. Otherwise, you end up with multiple Image objects for what is the same conceptual volume.

**Comment by pkcakeout** [comment]
> Otherwise, you end up with multiple Image objects for what is the same conceptual volume.

Exactly this is what I intended with the original implementation (if I understand you correctly). Let's take a slice-based DICOM-upload (RawImageUploadSession) with a varying slice spacing as an example:

My idea was normalize it all into slices into mhd for these cases and then construct multiple image representations of the same data. One representation would be:
 - 1 image per slice representing a single CT(?) slice
 - And one image that would describe the entire "varying slice spacing volume" that would then refer to all the other image files.

We can also rework this to "ImageFile" carrying the concept of an image (like thumbnail etc), but I would the call it "ImageRepresentation" or something similar, since I do not believe that 1-file 1-image(-representation) scales very well into the future (unless we allow zip files as a hacky crutch).

**Comment by jmsmkn** [comment]
Ok - that wasn't clear, and `Image` is now used as this concept as it's tied in to the Patient/Study models. `ImageFile` is many-to-one on `Image` so there's nothing to stop you from having many different types there.

**Comment by pkcakeout** [comment]
That is probably on me. This could have been written down in a proper design document. Oh well...
