### ISSUE TITLE
Removing admins is not possible

### ISSUE THREAD

**Issue by ecemlago** [comic/grand-challenge.org#804]
Deleting admins from a challenge is not possible. Admins should be able to remove other admins. This is necessary for example for educational challenges.

**Comment by jmsmkn** [comment]
It is possible - scroll to the right on the challenge admins page. You cannot remove yourself (ask another admin to do it), this is because we always need 1 admin for each challenge.

![Screenshot_20190501_093659](https://user-images.githubusercontent.com/12661555/57009090-d7e7dd80-6bf4-11e9-938e-3aea9650c7f6.png)
