### ISSUE TITLE
Retina API tests to fail with DRF 3.10

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#852]
See https://travis-ci.org/comic/grand-challenge.org/builds/562447770

Maybe from Django Rest Framework going from 3.9 to 3.10? https://github.com/comic/grand-challenge.org/compare/update_deps?expand=1#diff-46bb8405eeb4d8a11deb635f562f7c48R297

TODO:

- [ ] Fix tests
- [ ] Unpin `djangorestframework` in `Pipfile`
- [ ] `pipenv lock`

**Comment by jmsmkn** [comment]
> Maybe from Django Rest Framework going from 3.9 to 3.10? https://github.com/comic/grand-challenge.org/compare/update_deps?expand=1#diff-46bb8405eeb4d8a11deb635f562f7c48R297

Confirmed with https://travis-ci.org/comic/grand-challenge.org/builds/562453979

**Comment by HarmvZ** [comment]
The problem seems to be that the behavior of the`ModelSerializer` that serializes the `ETDRSGridAnnotation` model [here](https://github.com/comic/grand-challenge.org/blob/968070d5ac916c13f048a8d77ae9221af90963c7/app/grandchallenge/annotations/serializers.py#L48) has changed. It now adds an `allow_empty=False` statement to the `ListSerializer` that serializes the `ArrayField` if the arrayfield does not contain a `blank=True` value. I think this change has been made in this PR: https://github.com/encode/django-rest-framework/issues/6509 

To fix this I explicitly added a `blank=True` and `default=list` statement to the `optic_disk` `ArrayField` that is allowed to be an empty list (but not null). I guess I should probably have added this when I created the model but I thought then that an arrayfield is always allowed to be empty, which the test confirmed.
