### ISSUE TITLE
Add drf friendly views for chunked upload of images

### ISSUE THREAD

**Issue by haimasree** [comic/grand-challenge.org#883]

**Comment by jmsmkn** [comment]
In the branch https://github.com/comic/grand-challenge.org/tree/883_upload_drf I have made the drf view for chunked file uploads. I still have some things to do before we can merge it which will need to wait until I am back from vacation, but (@haimasree) you can now write the client code to create files.

You can see an example implementation of this in this test - https://github.com/comic/grand-challenge.org/blob/883_upload_drf/app/tests/jqfileupload_tests/test_api.py#L134 You will need to handle what happens if the response to any chunk is not 200 and up the chunk size to `2 ** 23`.

*TODO*

- [ ] Add in model permissions and drf filters so users can only see their own uploads (with tests)
- [ ] Check what the csrf_token field is for, I think that this can be replaced with a user id as auth is done elsewhere
- [ ] Add back file upload validation support (this needs to be configurable per widget somehow, but is only used in 1 place)
- [ ] Get the widget to use the drf view
