### ISSUE TITLE
Add workstation configuration app

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#943]
Users would like to set some defaults for a workstation. Add workstation configuration objects that are publicly readable.

Permissions: Workstation, Reader Study and Algorithm creators can add `WorkstationConfig`s. The creator of each config can edit it.

The models should minimally contain:

- `WorkstationConfig`
  - creator
  - title (str, required)
  - slug
  - description (str, optional)
  - window presets (m2m to `WindowPreset`)
  - default window preset (fk to `WindowPreset`)
  - ...extensions with default slab thickness (float), default renderMethod (choice field, Maximum, Minimum, Average), plugins (m2m to `Plugins`), tools (m2m to `WorkstationTools`)

- `WindowPreset`
  - title (str, required, unique)
  - slug
  - width (PositiveIntegerField, required)
  - center (IntegerField, required)

There should be a rest API so that the workstations can get the config objects and then configure themselves.

The workstation config should then be optionally set on a Workstation, Reader Study or Algorithm, and sent along as part of the query parameter to the session.

**Comment by nlessmann** [comment]
An option to customize the overlay would also be super useful. The default now shows the same or almost the same color for labels 1, 2, 3 etc., but often it is important to have different labels in distinct colors so that different objects in the image can be easily differentiated.

Default view direction would also be useful. For instance, spine scans are best viewed in sagittal mode, so it would be nice if the viewer could be configured to start in sagittal or coronal view rather than axial view.
