### ISSUE TITLE
Enable additional header information for 4DCT

### ISSUE THREAD

**Issue by AjayPatel86** [comic/grand-challenge.org#983]
For the implementation of the colormapping pipeline, additional header information must be read out of the mhd file that is uploaded. These are the contenttimes and mAs of the CTP acquisition, t0 and t1 values for the visualization.

**Comment by jmsmkn** [comment]
You should be able to do that within your container, I don't think that this needs anything on the grand challenge side. Please re-open if I'm mistaken.

**Comment by silvandeleemput** [comment]
@jmsmkn I think that we need to be able to do this on the grand challenge side as well. If we are at least uploading our images through grand-challenge and we pass our 4D CTP image to the algorithm, then it needs to contain the additional headers. However, these headers are discarded on upload currently. We should properly support these specific headers and test them for valid values.

**Comment by jmsmkn** [comment]
Ah OK, I thought that they weren't cleaned. Maybe add an allow list of headers that we keep, and only use ones where there cannot be any identifiable information.

**Comment by silvandeleemput** [comment]
Ok, the minimal header information we currently require is:

```
Exposures:List[float] (in mAs / time point)
ContentTimes:List[str]  (where str is timestamp in "HHMMSS.fff" / time point)
t0:float (begin timepoint in flow window, specific for colormapping algorithm)
t1:float (end timepoint in flow window, specific for colormapping algorithm)
```

I'll create a whitelist approach for this.

**Comment by silvandeleemput** [comment]
@jmsmkn Support for the above mentioned additional headers has been implemented. However, I would like to clear/remove all other non-standard non-whitelisted additional headers from the header file, after uploading. Sadly, this currently works this way for the 4D MHD loader, but not for the default SimpleITK loader, because the Image object created by the SImpleITK loader cannot remove the metadata keys after load. This issue also makes one test fail at the moment.

I see two solutions:
* Always use the 4D MHD loader (which also supports fewer dimensions), which constructs the SimpleITK Image from scratch and adds the correct metadata on load.
* Remove the headers from the MHD header after writing it with the SimpleITK .writeImage function and only store the modified MHD header (seems messier)

**Comment by jmsmkn** [comment]
All things equal using the same loader would be preferable.
